name:                habitscipline-api
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - mergeful
    - jose
    - persistent
    - servant
    - servant-auth
    - servant-auth-server
    - habitscipline-client-data
    - habitscipline-data
    - habitscipline-api-server-data
    - text
    - validity
    - validity-text
