name:                habitscipline-api
version:             0.0.0.0
github:              "NorfairKing/habitscipline-api-cli-login"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - mergeful
    - jose
    - persistent
    - servant
    - servant-auth
    - servant-auth-server
    - habitscipline-client-data
    - habitscipline-data
    - habitscipline-api-server-data
    - text
    - validity
    - validity-text
