name:                habitscipline-api-server-data-gen
version:             0.0.0.0
github:              "NorfairKing/habitscipline"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - bytestring
    - genvalidity
    - genvalidity-mergeful
    - genvalidity-persistent
    - genvalidity-text
    - habitscipline-api-server-data
    - habitscipline-data-gen
    - mergeful
    - password
    - text

tests:
  habitscipline-api-server-data-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-sydtest
    - sydtest
    - habitscipline-api-server-data
    - habitscipline-api-server-data-gen
