resolver: lts-19.6
packages:
- habitscipline-api
- habitscipline-api-gen
- habitscipline-api-server
- habitscipline-api-server-data
- habitscipline-api-server-data-gen
- habitscipline-api-server-gen
- habitscipline-cli
- habitscipline-client
- habitscipline-client-data
- habitscipline-data
- habitscipline-data-gen
- habitscipline-tui

# These are duplicated in nix/overlay.nix
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

extra-deps:
- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
  - typed-uuid
  - genvalidity-typed-uuid

- github: supki/envparse
  commit: de5944fb09e9d941fafa35c0f05446af348e7b4d

- github: NorfairKing/appendful
  commit: e6534d166e1596a7a94966d496cfafc02d3e993f
  subdirs:
  - appendful
  - appendful-persistent
  - genvalidity-appendful

- github: NorfairKing/mergeful
  commit: 832092b8ed706bd3b045d5106f96715a6f4ddc4a
  subdirs:
  - mergeful
  - mergeful-persistent
  - genvalidity-mergeful

- github: NorfairKing/cursor-brick
  commit: 5c1d1306632403a3dc11ddeda10deee932c0b307
  subdirs: 
    - cursor-brick

- github: NorfairKing/cursor
  commit: 5f18d58d1b34a752d24a94590c2cd35e8b6d557b
  subdirs: 
    - cursor
    - cursor-gen

- github: NorfairKing/validity
  commit: 2e9198bdaaa8c80a5dbe2b7b860b5c26558c6374
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-hashable
  - genvalidity-sydtest-lens
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector

- github: NorfairKing/autodocodec
  commit: e337d681109cac273f5b9ea2b54b174bce79d312
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml

- github: NorfairKing/safe-coloured-text
  commit: 675cb01fce5f46718416d7746de5b856ed90a63f
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 9db39de44641f28a2c26de80fcfe08616fcf3054
  subdirs:
    - sydtest
    - sydtest-discover
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-servant
    - sydtest-wai
    - sydtest-yesod


nix:
  packages:
    - zlib
    - haskellPackages.autoexporter
    - killall
