name:                habitscipline-tui
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - async
  - brick
  - containers
  - cursor
  - cursor-brick
  - directory
  - envparse
  - filelock
  - habitscipline-cli
  - habitscipline-client-data
  - habitscipline-data
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - text
  - time
  - vty
  - yaml
  - yamlparse-applicative

executables:
  habit:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - habitscipline-tui
