name:                habitscipline-data-gen
version:             0.0.0.0
github:              "NorfairKing/habitscipline"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - containers
    - genvalidity
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-path
    - genvalidity-text
    - genvalidity-time
    - genvalidity-typed-uuid
    - habitscipline-data
    - text
    - time

tests:
  habitscipline-data-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-persistent
    - habitscipline-data
    - habitscipline-data-gen
    - sydtest
    - path
    - path-io
    - yamlparse-applicative
