name:                habitscipline-api-server-data
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - autodocodec
    - autodocodec
    - habitscipline-data
    - mergeful
    - mergeful-persistent
    - password
    - password-instances
    - persistent
    - persistent-sqlite
    - persistent-template
    - text
    - time
    - validity
    - validity-persistent
    - validity-text
    - validity-time
