name:                habitscipline-data
version:             0.0.0.0
github:              "NorfairKing/habitscipline"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - base16
    - bytestring
    - containers
    - cryptohash-sha256
    - directory
    - filepath
    - path
    - path
    - path-io
    - persistent
    - random-shuffle
    - safe
    - text
    - time
    - typed-uuid
    - validity
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-text
    - validity-time
    - yaml
    - yamlparse-applicative
