name: "Nix Build"
on:
  pull_request:
  push:
    branches:
      - development
      - master

jobs:
  hooks:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        extra_nix_config: |
          system-features = kvm nixos-test benchmark big-parallel
    - uses: cachix/cachix-action@v7
      with:
        name: habit
        extraPullNames: validity,cursor,cursor-dirforest,mergeful,yamlparse
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build ci.nix

